### PR TITLE
transform Postgres SRC

### PR DESCRIPTION
**Pull request by akozichev**

### CODE REVIEW

**Review by akozichev — COMMENTED** [review]
looks ok

**Comment by ilikerashers** [comment]
Suggest copying camunda transform to postgres

**Comment by ilikerashers** [comment]
Approving. Better to use a layer of abstraction over source/destinations in future

**Review by ilikerashers — COMMENTED** [review]
Comments - better with abstraction layer

**Review by ilikerashers — APPROVED** [review]

**Pull request merged**
